// src/lib/training/scoringConstantsCatalog.ts
import { DEFAULT_TRAINING_SCORING_CONSTANTS, StatName } from "./scoring"

/** Tab grouping for the Advanced section. */
export type CatalogGroup = "priority" | "ratio" | "composition" | "bonuses" | "level" | "misc"

/** A single tunable multiplier entry shown as one slider row in the Advanced section. */
export interface ScoringConstantEntry {
    /** Settings key under the `training` namespace, matching what `scoringConstantsFromSettings` reads. */
    key: string
    /** Human label shown above the slider. */
    label: string
    /** One-line description, always visible. */
    description: string
    /** Which Advanced tab this belongs to. */
    group: CatalogGroup
    /** Default value sourced from `DEFAULT_TRAINING_SCORING_CONSTANTS`. */
    defaultValue: number
    /** Slider minimum. */
    min: number
    /** Slider maximum. */
    max: number
    /** Slider step. */
    step: number
    /** When set, entries in the same monotonic group are clamped relative to each other. */
    monotonicGroup?: string
}

const D = DEFAULT_TRAINING_SCORING_CONSTANTS

/** Catalog driving the Advanced section's slider rows. Order within each group is the rendered order. */
export const SCORING_CONSTANTS_CATALOG: ReadonlyArray<ScoringConstantEntry> = [
    // Priority group
    {
        key: "priorityCoefficient",
        label: "Priority coefficient",
        description: "Per-rank boost added to a stat's score for being higher in the priority list. Larger values make top-priority stats dominate.",
        group: "priority",
        defaultValue: D.priorityCoefficient,
        min: 0,
        max: 2,
        step: 0.05,
    },

    // Ratio group: 6 ascending breakpoints
    {
        key: "ratioBreakpoint1",
        label: "Ratio breakpoint 1",
        description: "First completion percentage where the ratio multiplier drops to the next bucket.",
        group: "ratio",
        defaultValue: D.ratioBreakpoints[0],
        min: 0,
        max: 200,
        step: 1,
        monotonicGroup: "ratio-breakpoints",
    },
    {
        key: "ratioBreakpoint2",
        label: "Ratio breakpoint 2",
        description: "Second completion percentage where the ratio multiplier drops to the next bucket.",
        group: "ratio",
        defaultValue: D.ratioBreakpoints[1],
        min: 0,
        max: 200,
        step: 1,
        monotonicGroup: "ratio-breakpoints",
    },
    {
        key: "ratioBreakpoint3",
        label: "Ratio breakpoint 3",
        description: "Third completion percentage where the ratio multiplier drops to the next bucket.",
        group: "ratio",
        defaultValue: D.ratioBreakpoints[2],
        min: 0,
        max: 200,
        step: 1,
        monotonicGroup: "ratio-breakpoints",
    },
    {
        key: "ratioBreakpoint4",
        label: "Ratio breakpoint 4",
        description: "Fourth completion percentage where the ratio multiplier drops to the next bucket.",
        group: "ratio",
        defaultValue: D.ratioBreakpoints[3],
        min: 0,
        max: 200,
        step: 1,
        monotonicGroup: "ratio-breakpoints",
    },
    {
        key: "ratioBreakpoint5",
        label: "Ratio breakpoint 5",
        description: "Fifth completion percentage where the ratio multiplier drops to the next bucket.",
        group: "ratio",
        defaultValue: D.ratioBreakpoints[4],
        min: 0,
        max: 200,
        step: 1,
        monotonicGroup: "ratio-breakpoints",
    },
    {
        key: "ratioBreakpoint6",
        label: "Ratio breakpoint 6",
        description: "Sixth completion percentage where the ratio multiplier drops to the next bucket.",
        group: "ratio",
        defaultValue: D.ratioBreakpoints[5],
        min: 0,
        max: 200,
        step: 1,
        monotonicGroup: "ratio-breakpoints",
    },

    // Ratio group: 7 descending values
    {
        key: "ratioValue1",
        label: "Ratio value 1",
        description: "Ratio multiplier applied to stats below the first breakpoint (lowest completion bucket).",
        group: "ratio",
        defaultValue: D.ratioValues[0],
        min: 0,
        max: 10,
        step: 0.1,
        monotonicGroup: "ratio-values",
    },
    {
        key: "ratioValue2",
        label: "Ratio value 2",
        description: "Ratio multiplier applied to stats in the second-lowest completion bucket.",
        group: "ratio",
        defaultValue: D.ratioValues[1],
        min: 0,
        max: 10,
        step: 0.1,
        monotonicGroup: "ratio-values",
    },
    {
        key: "ratioValue3",
        label: "Ratio value 3",
        description: "Ratio multiplier applied to stats in the middle completion bucket.",
        group: "ratio",
        defaultValue: D.ratioValues[2],
        min: 0,
        max: 10,
        step: 0.1,
        monotonicGroup: "ratio-values",
    },
    {
        key: "ratioValue4",
        label: "Ratio value 4",
        description: "Ratio multiplier applied to stats above the midpoint breakpoint.",
        group: "ratio",
        defaultValue: D.ratioValues[3],
        min: 0,
        max: 10,
        step: 0.1,
        monotonicGroup: "ratio-values",
    },
    {
        key: "ratioValue5",
        label: "Ratio value 5",
        description: "Ratio multiplier applied to stats nearing the upper completion buckets.",
        group: "ratio",
        defaultValue: D.ratioValues[4],
        min: 0,
        max: 10,
        step: 0.1,
        monotonicGroup: "ratio-values",
    },
    {
        key: "ratioValue6",
        label: "Ratio value 6",
        description: "Ratio multiplier applied to stats just below the over-target tier.",
        group: "ratio",
        defaultValue: D.ratioValues[5],
        min: 0,
        max: 10,
        step: 0.1,
        monotonicGroup: "ratio-values",
    },
    {
        key: "ratioValue7",
        label: "Ratio value 7",
        description: "Ratio multiplier applied to stats already past their target (over-target tier).",
        group: "ratio",
        defaultValue: D.ratioValues[6],
        min: 0,
        max: 10,
        step: 0.1,
        monotonicGroup: "ratio-values",
    },

    // Composition group
    {
        key: "statWeightWithBars",
        label: "Stat weight (with bars)",
        description: "Weight applied to the stat-efficiency score when the training has any relationship bars.",
        group: "composition",
        defaultValue: D.statWeightWithBars,
        min: 0,
        max: 1,
        step: 0.05,
    },
    {
        key: "relationshipWeightWithBars",
        label: "Relationship weight (with bars)",
        description: "Weight applied to the relationship score when the training has any relationship bars.",
        group: "composition",
        defaultValue: D.relationshipWeightWithBars,
        min: 0,
        max: 1,
        step: 0.05,
    },
    {
        key: "miscWeight",
        label: "Misc weight",
        description: "Weight applied to the misc score (skill hints etc.) in every composition.",
        group: "composition",
        defaultValue: D.miscWeight,
        min: 0,
        max: 1,
        step: 0.05,
    },

    // Bonuses group
    {
        key: "mainStatThresholdSpeed",
        label: "Main-stat threshold (Speed)",
        description: "Minimum Speed gain that triggers the main-stat bonus on Speed training.",
        group: "bonuses",
        defaultValue: D.mainStatThresholds[StatName.SPEED],
        min: 5,
        max: 60,
        step: 1,
    },
    {
        key: "mainStatThresholdStamina",
        label: "Main-stat threshold (Stamina)",
        description: "Minimum Stamina gain that triggers the main-stat bonus on Stamina training.",
        group: "bonuses",
        defaultValue: D.mainStatThresholds[StatName.STAMINA],
        min: 5,
        max: 60,
        step: 1,
    },
    {
        key: "mainStatThresholdPower",
        label: "Main-stat threshold (Power)",
        description: "Minimum Power gain that triggers the main-stat bonus on Power training.",
        group: "bonuses",
        defaultValue: D.mainStatThresholds[StatName.POWER],
        min: 5,
        max: 60,
        step: 1,
    },
    {
        key: "mainStatThresholdGuts",
        label: "Main-stat threshold (Guts)",
        description: "Minimum Guts gain that triggers the main-stat bonus on Guts training.",
        group: "bonuses",
        defaultValue: D.mainStatThresholds[StatName.GUTS],
        min: 5,
        max: 60,
        step: 1,
    },
    {
        key: "mainStatThresholdWit",
        label: "Main-stat threshold (Wit)",
        description: "Minimum Wit gain that triggers the main-stat bonus on Wit training.",
        group: "bonuses",
        defaultValue: D.mainStatThresholds[StatName.WIT],
        min: 5,
        max: 60,
        step: 1,
    },
    {
        key: "mainStatBonusMagnitude",
        label: "Main-stat bonus magnitude",
        description: "Multiplier applied to a stat's score when its gain reaches the main-stat threshold.",
        group: "bonuses",
        defaultValue: D.mainStatBonusMagnitude,
        min: 1,
        max: 5,
        step: 0.1,
    },

    // Level group
    {
        key: "levelBoostRank1Factor",
        label: "Level boost rank 1",
        description: "Level-amplifier factor for the user's #1 priority stat.",
        group: "level",
        defaultValue: D.levelBoostRank1Factor,
        min: 0,
        max: 2,
        step: 0.05,
    },
    {
        key: "levelBoostRank2Factor",
        label: "Level boost rank 2",
        description: "Level-amplifier factor for the user's #2 priority stat.",
        group: "level",
        defaultValue: D.levelBoostRank2Factor,
        min: 0,
        max: 2,
        step: 0.05,
    },
    {
        key: "levelBoostRank3Factor",
        label: "Level boost rank 3",
        description: "Level-amplifier factor for the user's #3 priority stat.",
        group: "level",
        defaultValue: D.levelBoostRank3Factor,
        min: 0,
        max: 2,
        step: 0.05,
    },

    // Misc group: everything else
    {
        key: "statWeightWithoutBars",
        label: "Stat weight (no bars)",
        description: "Weight applied to the stat-efficiency score when the training has no relationship bars.",
        group: "misc",
        defaultValue: D.statWeightWithoutBars,
        min: 0,
        max: 1,
        step: 0.05,
    },
    {
        key: "relationshipOrangeValue",
        label: "Relationship orange value",
        description: "Base relationship value contributed by an orange (maxed) friendship bar.",
        group: "misc",
        defaultValue: D.relationshipOrangeValue,
        min: 0,
        max: 10,
        step: 0.1,
    },
    {
        key: "relationshipGreenValue",
        label: "Relationship green value",
        description: "Base relationship value contributed by a green friendship bar.",
        group: "misc",
        defaultValue: D.relationshipGreenValue,
        min: 0,
        max: 10,
        step: 0.1,
    },
    {
        key: "relationshipBlueValue",
        label: "Relationship blue value",
        description: "Base relationship value contributed by a blue friendship bar.",
        group: "misc",
        defaultValue: D.relationshipBlueValue,
        min: 0,
        max: 10,
        step: 0.1,
    },
    {
        key: "relationshipDiminishingFactor",
        label: "Relationship diminishing factor",
        description: "Diminishing-returns coefficient: relationship value decays by `fillPercent * this` as bars fill up.",
        group: "misc",
        defaultValue: D.relationshipDiminishingFactor,
        min: 0,
        max: 2,
        step: 0.05,
    },
    {
        key: "relationshipEarlyGameBonus",
        label: "Relationship early-game bonus",
        description: "Multiplier applied to relationship scores during Pre-Debut and Junior year to favor early relationship building.",
        group: "misc",
        defaultValue: D.relationshipEarlyGameBonus,
        min: 1,
        max: 3,
        step: 0.05,
    },
    {
        key: "relationshipTrainerSupportBonus",
        label: "Relationship trainer-support bonus",
        description: "Multiplier applied to relationship bars belonging to trainer-support characters.",
        group: "misc",
        defaultValue: D.relationshipTrainerSupportBonus,
        min: 1,
        max: 2,
        step: 0.05,
    },
    {
        key: "skillHintPerHintScore",
        label: "Skill hint per-hint score",
        description: "Per-hint score added to the misc score for each detected skill hint.",
        group: "misc",
        defaultValue: D.skillHintPerHintScore,
        min: 0,
        max: 100,
        step: 1,
    },
    {
        key: "skillHintOverrideScore",
        label: "Skill hint override score",
        description: "Override score returned by misc scoring when 'prioritize skill hints' is enabled and any are present.",
        group: "misc",
        defaultValue: D.skillHintOverrideScore,
        min: 0,
        max: 100000,
        step: 100,
    },
    {
        key: "juniorEarlyGameFlatBonus",
        label: "Junior early-game flat bonus",
        description: "Flat bonus added to scores during Junior early-game turns to bias toward early progression.",
        group: "misc",
        defaultValue: D.juniorEarlyGameFlatBonus,
        min: 0,
        max: 1000,
        step: 10,
    },
    {
        key: "relationshipScale",
        label: "Relationship scale",
        description: "Final relationship-score scale factor applied after weighting.",
        group: "misc",
        defaultValue: D.relationshipScale,
        min: 0,
        max: 5,
        step: 0.05,
    },
    {
        key: "rainbowMultiplierEnabled",
        label: "Rainbow multiplier (enabled)",
        description: "Rainbow multiplier when the rainbow training bonus is on and the trainee is in Year 2+ with rainbows.",
        group: "misc",
        defaultValue: D.rainbowMultiplierEnabled,
        min: 1,
        max: 5,
        step: 0.1,
    },
    {
        key: "rainbowMultiplierDisabled",
        label: "Rainbow multiplier (disabled)",
        description: "Rainbow multiplier when rainbows are present in Year 2+ but the rainbow training bonus setting is off.",
        group: "misc",
        defaultValue: D.rainbowMultiplierDisabled,
        min: 1,
        max: 5,
        step: 0.1,
    },
    {
        key: "rainbowPerInstanceBase",
        label: "Rainbow per-instance base",
        description: "Base value used when computing per-instance rainbow scaling for multi-rainbow trainings.",
        group: "misc",
        defaultValue: D.rainbowPerInstanceBase,
        min: 0,
        max: 1000,
        step: 10,
    },
    {
        key: "rainbowPerInstanceDecay",
        label: "Rainbow per-instance decay",
        description: "Decay coefficient applied to additional rainbow instances after the first.",
        group: "misc",
        defaultValue: D.rainbowPerInstanceDecay,
        min: 0,
        max: 2,
        step: 0.05,
    },
    {
        key: "anticipatoryMinFillPercent",
        label: "Anticipatory min fill percent",
        description: "Minimum bar fill percent a green or blue bar must have to qualify for the anticipatory rainbow multiplier.",
        group: "misc",
        defaultValue: D.anticipatoryMinFillPercent,
        min: 0,
        max: 100,
        step: 1,
    },
    {
        key: "anticipatoryCoefficient",
        label: "Anticipatory coefficient",
        description: "Coefficient applied to summed bar contributions when computing the anticipatory rainbow multiplier.",
        group: "misc",
        defaultValue: D.anticipatoryCoefficient,
        min: 0,
        max: 2,
        step: 0.05,
    },
    {
        key: "anticipatoryCap",
        label: "Anticipatory cap",
        description: "Maximum extra multiplier the anticipatory rainbow bonus can contribute (kept below the real rainbow multiplier).",
        group: "misc",
        defaultValue: D.anticipatoryCap,
        min: 0,
        max: 2,
        step: 0.05,
    },
]
